name: iOS CI & Deploy

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: macos-latest

    steps:

      - name: Run Fastlane (beta)
        run: cd fastlane
        run: fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
