name: Run Fastlane Beta on Master Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest 

    steps:
      - name: List available simulators
        run: xcrun simctl list devices
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Startup Simulator
        run: xcrun simctl boot 'iPhone 16 Pro' || true

      - name: Select Xcode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Setup Keychain
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings build.keychain

      - name: Fastlane Match
        run: bundle exec fastlane match appstore --readonly --git_url "$CERTS_REPO_URL"
        env:
          CERTS_REPO_URL: ${{ secrets.CERTS_REPO_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }} 
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          APP_IDENTIFIER: com.marcell.Tempus

      - name: List installed provisioning profiles
        run: ls -al ~/Library/MobileDevice/Provisioning\ Profiles
          
      - name: Xcodebuild Diagnostics
        run: xcodebuild -showBuildSettings -project Tempus.xcodeproj -scheme Tempus
        
      - name: Run Fastlane Test and Deployment
        run: bundle exec fastlane beta --verbose
        env:
          CERTS_REPO_URL: ${{ secrets.CERTS_REPO_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          APP_IDENTIFIER: com.marcell.Tempus
          
      
