name: iOS CI & Deploy

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Run unit tests
        run: |
          xcodebuild \
            -scheme YourAppScheme \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            clean test \
            ONLY_ACTIVE_ARCH=YES

      - name: Run Fastlane
        run: |
          bundle exec fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
