name: Run Fastlane Beta on Master Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest 

    steps:
      - name: List available simulators
        run: xcrun simctl list devices
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Startup Simulator
        run: xcrun simctl boot 'iPhone 16 Pro' || true

      - name: Select Xcode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Install SwiftLint
        run: brew install swiftlint
        
      - name: Fix SwiftLint config file permissions
        run: chmod 644 .swiftlint.yml

      - name: Run Swiftlint
        run: swiftlint

      - name: Create & Unlock Temporary Keychain
        run: |
          security create-keychain -p "temp_pass" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "temp_pass" build.keychain
          security set-keychain-settings -lut 21600 build.keychain

      - name: Debug Credentials
        run: |
          echo "APPLE_ID: $APPLE_ID"
          echo "FASTLANE_USER: $FASTLANE_USER"
          echo "FASTLANE_USER length: ${#FASTLANE_USER}"
          echo "FASTLANE_PASSWORD length: ${#FASTLANE_PASSWORD}"
          echo "FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD length: ${#FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD}"
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }} 
          FASTLANE_USER: ${{ secrets.APPLE_ID }}

      - name: Fastlane Match
        run: bundle exec fastlane match appstore --readonly --git_url "$CERTS_REPO_URL" --keychain_name build.keychain --keychain_password temp_pass
        env:
          CERTS_REPO_URL: ${{ secrets.CERTS_REPO_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }} 
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          APP_IDENTIFIER: com.marcell.Tempus

      - name: Fastlane Spaceauth
        run: bundle exec fastlane spaceauth
        env: 
          CERTS_REPO_URL: ${{ secrets.CERTS_REPO_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        #  FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          APP_IDENTIFIER: com.marcell.Tempus

      - name: List installed provisioning profiles
        run: ls -al ~/Library/MobileDevice/Provisioning\ Profiles
          
      - name: Xcodebuild Diagnostics
        run: xcodebuild -showBuildSettings -project Tempus.xcodeproj -scheme Tempus
        
      - name: Run Fastlane Test and Deployment
        run: bundle exec fastlane beta --verbose
        env:
          CERTS_REPO_URL: ${{ secrets.CERTS_REPO_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          # FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          APP_IDENTIFIER: com.marcell.Tempus
          # SPACESHIP_CONNECT_API_TOKEN: "" # Force it to not use SIRP 
          
      
