name: iOS CI & Deploy

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: macos-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run unit tests
        run: |
          xcodebuild \
            -scheme Tempus \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.5' \
            clean test \
            ONLY_ACTIVE_ARCH=YES

      - name: Run Fastlane (beta)
        run: bundle exec fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
